os:
  - linux
  - osx
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '8'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CC=gcc-4.9; fi'
before_script:
  - npm install winston@2.3.1
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
  - cp -R build/* ./
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libavahi-compat-libdnssd-dev
